blank_issues_enabled: false
contact_links:
  - name: WeKnora 문서
    url: https://github.com/Tencent/WeKnora/blob/main/docs/QA.md
    about: WeKnora 자주 묻는 질문(FAQ) 확인
  - name: 토론 구역
    url: https://github.com/Tencent/WeKnora/discussions
    about: 토론 구역에서 질문하거나 아이디어 공유
